name: stackorange

services:
  traefik:
    image: traefik:v3.3
    command: --providers.docker
    restart: unless-stopped
    environment:
      CF_API_EMAIL: ${CF_API_EMAIL}
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./.certs:/var/traefik/certs:rw
    networks:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./.db:/app/db
      - ./.lnd/data/chain/bitcoin/mainnet/admin.macaroon:/app/lnd/admin.macaroon:ro
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - app
      - lightning
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.rule=Host(`stackorange.com`)
      - traefik.http.routers.app.entrypoints=websecure
      - traefik.http.routers.app.tls=true
      - traefik.http.routers.app.tls.certresolver=cloudflare
    environment:
      DATABASE_URL: ${DATABASE_URL}
      LND_REST_ENDPOINT: ${LND_REST_ENDPOINT}
      LND_GRPC_ENDPOINT: ${LND_GRPC_ENDPOINT}
      LND_MACAROON_PATH: ${LND_MACAROON_PATH}
      LND_TLS_PATH: ${LND_TLS_PATH}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
    # depends_on:
    #   - lnd

  bitcoind:
    build:
      context: .
      dockerfile: bitcoin-core.Dockerfile
    restart: unless-stopped
    volumes:
      - ./.bitcoin:/home/bitcoin/.bitcoin
    networks:
      - bitcoin

  lnd:
    image: lightninglabs/lnd:v0.18.5-beta
    restart: unless-stopped
    volumes:
      - ./.lnd:/root/.lnd
    networks:
      - bitcoin
      - lightning
    depends_on:
      - bitcoind

networks:
  app:
  bitcoin:
  lightning:
