name: stackorange

services:
  traefik:
    image: traefik:v3.3
    command: --providers.docker
    environment:
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./.certs:/var/traefik/certs:rw

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./.db:/app/db
    ports:
      - "3000:3000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.rule=Host(`stackorange.com`)
      - traefik.http.routers.app.entrypoints=websecure
      - traefik.http.routes.app.tls=true
      - traefik.http.routes.app.tls.certresolver=cloudflare
    environment:
      DATABASE_URL: ${DATABASE_URL}
      LND_REST_API_ENDPOINT: ${LND_REST_API_ENDPOINT}
      LND_MACAROON_PATH: ${LND_MACAROON_PATH}
    depends_on:
      - lnd

  bitcoind:
    build:
      context: .
      dockerfile: bitcoin-core.Dockerfile
    restart: unless-stopped
    volumes:
      - ./.bitcoin:/home/bitcoin/.bitcoin

  lnd:
    image: lightninglabs/lnd:v0.18.5-beta
    restart: unless-stopped
    volumes:
      - ./.lnd:/root/.lnd
    depends_on:
      - bitcoind
