name: stackorange

services:
  traefik:
    image: traefik:v3.3
    command: --providers.docker
    environment:
      CF_API_EMAIL: ${CF_API_EMAIL}
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./.certs:/var/traefik/certs:rw
    networks:
      - app
      - plausible

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./.db:/app/db
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - app
      - lightning
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.rule=Host(`stackorange.com`)
      - traefik.http.routers.app.entrypoints=websecure
      - traefik.http.routers.app.tls=true
      - traefik.http.routers.app.tls.certresolver=cloudflare
    environment:
      DATABASE_URL: ${DATABASE_URL}
      LND_REST_API_ENDPOINT: ${LND_REST_API_ENDPOINT}
      LND_MACAROON_PATH: ${LND_MACAROON_PATH}
    # depends_on:
    #   - lnd

  bitcoind:
    build:
      context: .
      dockerfile: bitcoin-core.Dockerfile
    restart: unless-stopped
    volumes:
      - ./.bitcoin:/home/bitcoin/.bitcoin
    networks:
      - bitcoin

  lnd:
    image: lightninglabs/lnd:v0.18.5-beta
    restart: unless-stopped
    volumes:
      - ./.lnd:/root/.lnd
    networks:
      - bitcoin
      - lightning
    depends_on:
      - bitcoind

  plausible_db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - ./.plausible/db-data:/var/lib/postgresql/data
    networks:
      - plausible
    environment:
      - POSTGRES_PASSWORD=${PLAUSIBLE_POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 1m

  plausible_events_db:
    image: clickhouse/clickhouse-server:24.3.3.102-alpine
    restart: always
    volumes:
      - ./.plausible/event-data:/var/lib/clickhouse
      - ./.plausible/event-logs:/var/log/clickhouse-server
      - ./.plausible/clickhouse/logs.xml:/etc/clickhouse-server/config.d/logs.xml:ro
      # This makes ClickHouse bind to IPv4 only, since Docker doesn't enable IPv6 in bridge networks by default.
      # Fixes "Listen [::]:9000 failed: Address family for hostname not supported" warnings.
      - ./.plausible/clickhouse/ipv4-only.xml:/etc/clickhouse-server/config.d/ipv4-only.xml:ro
      # This makes ClickHouse consume less resources, which is useful for small setups.
      # https://clickhouse.com/docs/en/operations/tips#using-less-than-16gb-of-ram
      - ./.plausible/clickhouse/low-resources.xml:/etc/clickhouse-server/config.d/low-resources.xml:ro
    networks:
      - plausible
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 -O - http://127.0.0.1:8123/ping || exit 1"]
      start_period: 1m

  plausible:
    image: ghcr.io/plausible/community-edition:v2.1.5
    restart: always
    command: sh -c "/entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      plausible_db:
        condition: service_healthy
      plausible_events_db:
        condition: service_healthy
    volumes:
      - ./.plausible/plausible-data:/var/lib/plausible
    ports:
      - 127.0.0.1:8000:8000
    networks:
      - plausible
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    labels:
      - traefik.enable=true
      - traefik.http.routers.plausible.rule=Host(`plausible.stackorange.com`)
      - traefik.http.routers.plausible.entrypoints=websecure
      - traefik.http.routers.plausible.tls=true
      - traefik.http.routers.plausible.tls.certresolver=cloudflare
    environment:
      - TMPDIR=/var/lib/plausible/tmp
      # required: https://github.com/plausible/community-edition/wiki/configuration#required
      - BASE_URL=${BASE_URL}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      # optional: https://github.com/plausible/community-edition/wiki/configuration#optional
      # registration: https://github.com/plausible/community-edition/wiki/configuration#registration
      - TOTP_VAULT_KEY
      - DISABLE_REGISTRATION=true
      - ENABLE_EMAIL_VERIFICATION
      # web: https://github.com/plausible/community-edition/wiki/configuration#web
      - HTTP_PORT
      - HTTPS_PORT
      # databases: https://github.com/plausible/community-edition/wiki/configuration#database
      - DATABASE_URL=${PLAUSIBLE_DATABASE_URL}
      - CLICKHOUSE_DATABASE_URL
      # Google: https://github.com/plausible/community-edition/wiki/configuration#google
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      # geolocation: https://github.com/plausible/community-edition/wiki/configuration#ip-geolocation
      - IP_GEOLOCATION_DB
      - GEONAMES_SOURCE_FILE
      - MAXMIND_LICENSE_KEY
      - MAXMIND_EDITION
      # email: https://github.com/plausible/community-edition/wiki/configuration#email
      - MAILER_ADAPTER
      - MAILER_EMAIL
      - MAILER_NAME
      - SMTP_HOST_ADDR
      - SMTP_HOST_PORT
      - SMTP_USER_NAME
      - SMTP_USER_PWD
      - SMTP_HOST_SSL_ENABLED
      - POSTMARK_API_KEY
      - MAILGUN_API_KEY
      - MAILGUN_DOMAIN
      - MAILGUN_BASE_URI
      - MANDRILL_API_KEY
      - SENDGRID_API_KEY

networks:
  app:
  bitcoin:
  lightning:
  plausible:
